---
labels:
  - name: needs rework
    description: "Needs rework"
    documentation: |
      An issue has only been opened as a placeholder or is filled with too
      little content and needs more content before it can go into processing.
    color: "b60205"
  - name: bug
    description: "Something isn't working"
    color: "d73a4a"
  - name: discussion
    description: "A topic that needs to be discussed"
    color: "98ff98"
  - name: documentation
    description: "Improvements or additions to documentation"
    color: "0075ca"
  - name: duplicate
    description: "This issue or pull request already exists"
    color: "cfd3d7"
  - name: enhancement
    description: "New feature or request"
    color: "a2eeef"
  - name: good first issue
    description: "Good for newcomers"
    color: "7057ff"
  - name: help wanted
    description: "Extra attention is needed"
    color: "008672"
  - name: invalid
    description: "This doesn't seem right"
    color: "e4e669"
  - name: question
    description: "Further information is requested"
    color: "d876e3"
  - name: SCS
    description: "Sovereign Cloud Stack"
    color: "96C68A"
  - name: support
    description: "Support request"
    color: "e99695"
  - name: wontfix
    description: "This will not be worked on"
    color: "ffffff"
  - name: on hold
    description: "Is on hold"
    color: "000000"
  - name: upstream
    description: "Implemented directly in the upstream"
    color: "0052cc"
  - name: infrastructure
    description: "Is related to the internal infrastructure"
    color: "2B3AA2"
  - name: housekeeping
    description: "Das bisschen Haushalt..."
    color: "d93f0b"
  - name: dependencies
    description: "Pull requests that update a dependency file"
    color: "0366d6"
  - name: security
    description: "Has to do with security"
    color: "fc0000"
  - name: work in progress
    description: "Pull requests that are work in progress, do not merge them"
    color: "c5def5"
  - name: refactoring
    description: "Improving something without adding new or changing existing functionality"
    color: "b9e1c3"
  - name: zuul
    description: "Release the dragons, run Zuul CI"
    color: "3cf7be"
  - name: renovate
    description: "PR created by Renovate"
    color: "#28163a"
