---
- hosts: localhost
  connection: local

  vars:
    github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') }}"
    gitstyring_root_dir: .
    log: false

  tasks:
    # - name: Manage people
    #   opentelekomcloud.gitcontrol.members:
    #     root: "{{ gitstyring_root_dir }}"
    #     token: "{{ github_token }}"

    # - name: Manage teams
    #   opentelekomcloud.gitcontrol.teams:
    #     root: "{{ gitstyring_root_dir }}"
    #     token: "{{ github_token }}"

    - name: Manage repositories
      opentelekomcloud.gitcontrol.repositories:
        root: "{{ gitstyring_root_dir }}"
        token: "{{ github_token }}"
      no_log: "{{ log }}"
